  version: 1.0.{build}
  image: Visual Studio 2013
  init:
    - git config --global core.autocrlf input
  clone_folder: c:\projects\netmap
  before_build: cd WINDOWS
  build_script: c:\projects\netmap\build.bat
  build: off
  after_build: c:\projects\netmap\artifacts.bat
  artifacts:
    - path: c:\projects\netmap\myapp.zip
      name: MyApp